apiVersion: "v1"
kind: "BuildConfig"
metadata:
    labels:
      application: liberty-jenkins-pipeline
    name: "liberty-jenkins-pipeline"
    namespace: "liberty"
spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/Cuball0/s2i-liberty.git"
        ref: "master"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath:  Jenkinsfile
        env:
        - name: "APPLICATION_SOURCE_REPO"
          value: "https://github.com/efsavage/hello-world-war.git"
