apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2018-11-08T15:05:57Z'
  labels:
    app: s2i-liberty-binary-app
  name: s2i-liberty-binary-app
  namespace: liberty
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-liberty-binary-app:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
      binary: {}
      type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 's2i-liberty-builder:latest'
        namespace: liberty
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: lmfV6mzALuiAO2gwl5gX
      type: GitHub
    - generic:
        secret: U3Je99FDUE94F8Fv2Les
      type: Generic
    - type: ConfigChange
    - imageChange:
      type: ImageChange
status:
  lastVersion: 1
